version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8000
    image: frontend.app:dev
    container_name: frontend
    ports:
      - "3000:80"

