version: "3.9"
services:
  pg:
    image: postgres:16-alpine
    container_name: payment-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: catalog_admin
      POSTGRES_PASSWORD: P@ssw0rd!
      POSTGRES_DB: catalog
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  payment.api:
    build:
      context: .
      dockerfile: Dockerfile
    image: payment.api:dev
    container_name: payment-api
    depends_on:
      - pg
    restart: unless-stopped
    environment:
      ConnectionStrings__PaymentDb: "Host=pg;Port=5432;Database=catalog;Username=catalog_admin;Password=P@ssw0rd!"
    ports:
      - "7001:7001"
      - "7002:8080"

volumes:
  pgdata:
