version: "3.9"
services:
  pg:
    image: postgres:16-alpine
    container_name: order-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: catalog_admin
      POSTGRES_PASSWORD: P@ssw0rd!
      POSTGRES_DB: catalog
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  order.api:
    build:
      context: .
      dockerfile: Dockerfile
    image: order.api:dev
    container_name: order-api
    depends_on:
      - pg
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__OrderDb: "Host=pg;Port=5432;Database=catalog;Username=catalog_admin;Password=P@ssw0rd!"
    ports:
      - "5002:80"

volumes:
  pgdata:
