name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: catalog_admin
          POSTGRES_PASSWORD: P@ssw0rd!
          POSTGRES_DB: catalog
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U catalog_admin" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Security tests
        run: |
          cd services/Security
          ./gradlew test --no-daemon
      - name: Order tests
        run: |
          cd services/Order
          dotnet test
      - name: Payment tests
        run: |
          cd services/Payment
          go test ./...
