name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Restore dependencies
        run: dotnet restore

      - name: Run .NET tests
        run: |
          for proj in services/*/*.Tests/*.csproj; do
            dotnet test "$proj" --no-build --no-restore
          done

      - name: Run Go tests
        run: |
          cd services/Payment && go test ./...

      - name: Build Docker images
        run: |
          cd services && docker compose build
